AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Layers-Demo Application
Globals:
  Function:
    Timeout: 60
    AutoPublishAlias: releaseM2M1F1
Resources:
  TestRegisterInstanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Test_registerInstance
      Description: test register instance
      Role: arn:aws:iam::005595135841:role/DRLambdaRDSFullAccess
      CodeUri: s3://deepr-cms-lambda/93597578b1d6d6b2dc37e2fb693ff7d2
      Handler: CMS_registerInstance.lambda_handler
      Runtime: python3.7
      Layers:
      - Ref: MyLambdaLayer
  MyLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLambdaLayer
      Description: My Lambda Layer with Deserialize Function, Objectpath Module &
        AWS Regions JSON
      ContentUri: s3://deepr-cms-lambda/16cfa1d8404ffae4cdab8207bd462d9f
      CompatibleRuntimes:
      - python3.6
      - python3.7
      RetentionPolicy: Retain
Outputs:
  MyLambdaLayerARN:
    Value:
      Ref: MyLambdaLayer
    Description: MyLambdaLayer ARN
    Export:
      Name: my-lambda-layer-arn
  TestRegisterInstanceFunction:
    Description: function for CMS console
    Value:
      Fn::GetAtt:
      - TestRegisterInstanceFunction
      - Arn
